language: python
python:
  - "3.6"
services:
  - docker
install:
  - pip install -r test-requirements.txt
  - flake8 . --max-line-length=127
  - docker build -t max-question-answering-web-app .
  - docker run -it -d -p 8000:8000 max-question-answering-web-app
script:
  - docker ps | grep max-question-answering-web-app
